export const translations = {
    English: {
        home: "Home",
        game: "Game",
        settings: "Settings",
        results: "Results",
        start: "Start Game",
        score: "Score",
        time: "Time",
        gameOver: "Game Over",
        save: "Save & Finish",
        language: "Language",
        theme: "Theme",
        difficulty: "Difficulty",
        backHome: "Back to Home",
        playAgain: "Play Again",
        changeSettings: "Change Settings",
        noResults: "No results yet",
    },

    Eesti: {
        home: "Avaleht",
        game: "Mäng",
        settings: "Seaded",
        results: "Tulemused",
        start: "Alusta mängu",
        score: "Tulemus",
        time: "Aeg",
        gameOver: "Mäng läbi",
        save: "Salvesta",
        language: "Keel",
        theme: "Teema",
        difficulty: "Raskusaste",
        backHome: "Tagasi avalehele",
        playAgain: "Mängi uuesti",
        changeSettings: "Muuda seadeid",
        noResults: "Tulemusi veel pole",
    },

    Russian: {
        home: "Главная",
        game: "Игра",
        settings: "Настройки",
        results: "Результаты",
        start: "Начать игру",
        score: "Счёт",
        time: "Время",
        gameOver: "Игра окончена",
        save: "Сохранить",
        language: "Язык",
        theme: "Тема",
        difficulty: "Сложность",
        backHome: "Назад домой",
        playAgain: "Играть снова",
        changeSettings: "Изменить настройки",
        noResults: "Результатов пока нет",
    }
};